### ISSUE TITLE
Opening Config Menu Crashes Minecraft

### ISSUE THREAD

**Issue by ghost** [Warriorrrr/EarthMCEssentials#13]
Hi, when I play on earthmc and try to toggle the menu, my minecraft crashes. I changed the keybind for opening the config menu to confirm and yes, it is the config menu that crashes the game. I'm using fabric loader 14.10, and the PolyMC launcher client.

**Comment by ghost** [comment]
"Process exited with code 255"
Crash report attached
[crash-2022-11-17_14.35.43-client.txt](https://github.com/EarthMC-Toolkit/EarthMCEssentials/files/10035433/crash-2022-11-17_14.35.43-client.txt)

**Comment by Owen3H** [comment]
Hi, thanks for the report.

The log you provided doesn't point to anything directly relating to EMCE.
What I understand is that one of the methods in ClothConfig has been updated and EMCE is trying to use the external jar instead of the one bundled, there could be a solution to this in future but I'm not sure as of now.

I would recommend you roll back to a lower ClothConfig version that EMCE supports (`8.2.88` officially).
In the meantime, I will work on updating to ClothConfig v9.
